account/urls.py
from django.urls import path
from .views import *

app_name = "account"
urlpatterns = [
    path("login/", loginView, name="login"),
    path("sign_up/", signUp, name="signUp"),
    path("logout/", logoutView, name="logout"),

    # user
    path("profile/", userProfile, name="userProfile"),
    path("update/profile/", updateUserProfile, name="updateUserProfile"),
    path("change/password/", changeUserPassword, name="changeUserPassword"),
]

channel/urls.py
from django.urls import path
from .views import *


app_name = "channel"
urlpatterns = [
    path('channels/', channelList, name="channelList"),
    path('detail/<int:id>/', channelDetail, name="channelDetail"),
    path("create_channel/", createChannel, name="createChannel"),
    path("update_channel/<int:id>/", updateChannel, name="updateChannel"),
    path("delete_channel/<int:id>/", deleteChannel, name="deleteChannel"),

    # subscriptions
    path('subscriptons/', subscriptionsList, name="subscriptonsList"),

    path('channel/subscribe/<int:id>/', subscribeView, name="subscribeChannel"),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("video.urls")),
    path('channel/', include("channel.urls")),
    path('account/', include("account.urls")),
]

handler404 = "main.views.page_not_found_view"


static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from .views import *


app_name = "video"
urlpatterns = [
    path('', index, name="index"),
    path('watch/<slug:slug>/', videoDetail, name="detail"),
    path('create/video/', createVideo, name="createVideo"),
    path('delete/video/<int:id>/<slug:slug>/', deleteVideo, name="deleteVideo"),
    path('update/video/<int:id>/<slug:slug>/', updateVideo, name="updateVideo"),

    # sub and like
    path('watch/like/<int:id>/', likeView, name="likeVideo"),

    # library
    path('library/', userLibrary, name="userLibrary"),
    path('library/<int:id>/', userLibraryVideos, name="userLibraryVideos"),
    path('create/library/', userLibraryCreate, name="userLibraryCreate"),
    path('update/library/<int:id>/', userLibraryUpdate, name="userLibraryUpdate"),
    path('delete/library/<int:id>/', userLibraryDelete, name="userLibraryDelete"),

    path('add/library/video/<int:id>/<int:video_id>/', addLibraryVideo, name="addLibraryVideo"),
    path('remove/library/video/<int:id>/<int:video_id>/', removeLibraryVideo, name="removeLibraryVideo"),


    # like videos authorVideos
    path('like/videos', likeVideos, name="likeVideoList"),

    # author
    path('author/videos/', authorVideos, name="authorVideos"),

]

templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index, follow">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="English">
    <meta name="description" content="{% block description %}{% endblock description %}"/>
    <meta name="keywords" content="{% block keywords %}{% endblock keywords %}" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">

    <link rel="shortcut icon" href="https://www.youtube.com/s/desktop/01f7cad5/img/favicon.ico" type="image/x-icon">
    <title>{% block title %}{% endblock title %}YouTube Clone</title>
    <style>
      body{
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
      }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body class="font-monospace">
    {% include 'base/navbar.html' %}
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/base/message.html
{% if messages %}
    {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}" role="alert" {% endif %}>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/base/navbar.html
{% load static %}
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'video:index' %}">
            <img src="{% static 'images/logo.png' %}" alt="YotuTube Clone" width="120" height="30">
          </a>
        </div>
      </nav>
        <div class="dropdown nav col-12 col-lg-auto me-lg-auto ml-3 justify-content-center mb-md-0">
          <a style="background-color: transparent;" class="d-flex align-items-center col-lg-4 mb-2 mb-lg-0 link-dark text-decoration-none dropdown-toggle list-group-item list-group-item-action text-light" id="dropdownNavLink" data-bs-toggle="dropdown" aria-expanded="false">
            Menu
          </a>
          <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownNavLink">
            <li><a class="dropdown-item" href="{% url 'video:index' %}" aria-current="page"><i class="fa-brands fa-youtube"></i> Home</a></li>
            <li><a class="dropdown-item {% if 'channels' in request.path %}active{% endif %}" href="{% url 'channel:channelList' %}"><i class="fa-solid fa-border-all"></i> All Channels</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item {% if 'author' in request.path %}active{% endif %}" href="{% url 'video:authorVideos' %}"><i class="fa-solid fa-clapperboard"></i> Your Videos</a></li>
            <li><a class="dropdown-item {% if 'library' in request.path %}active{% endif %}" href="{% url 'video:userLibrary' %}"><i class="fa-solid fa-photo-film"></i> Library</a></li>
            <li><a class="dropdown-item {% if 'like' in request.path %}active{% endif %}" href="{% url 'video:likeVideoList' %}"><i class="fa-solid fa-heart"></i> Your Favorite Videos</a></li>
            <li><a class="dropdown-item {% if 'subscriptons' in request.path %}active{% endif %}" href="{% url 'channel:subscriptonsList' %}"><i class="fa-solid fa-film"></i> Subscriptions</a></li>
          </ul>
        </div>
      
      <form class="col-12 col-lg mb-3 mb-lg-0 me-lg-3" action="/" role="search" method="GET">
        <input type="search" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Search..." aria-label="Search">
      </form>
      {% if request.user.is_authenticated %}
      <div class="dropdown text-end">
        {% if request.user.channel %}
        <a href="#" class="d-block link-dark text-decoration-none text-light dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="{{request.user.channel.avatar.url}}" alt="{{request.user.username}}" width="50" height="50" class="rounded-circle">
        </a>
        {% else %}
        <a href="#" class="d-block link-dark text-decoration-none text-light dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="{% static 'images/channel/avatar/avatar.png' %}" alt="{{request.user.username}}" width="50" height="50" class="rounded-circle">
        </a>
        {% endif %}
        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
          <li><a class="dropdown-item" href="{% url 'account:userProfile' %}">{{request.user.get_full_name}}</a></li>
          <li><a class="dropdown-item" href="{% url 'video:createVideo' %}"><i class="fa-solid fa-video"></i> New Video</a></li>
          <li><a class="dropdown-item" href="{% url 'account:updateUserProfile' %}"><i class="fa-solid fa-gear"></i> Settings</a></li>
          <li><a class="dropdown-item" href="{% url 'account:userProfile' %}"><i class="fa-solid fa-user"></i> Profile</a></li>
          {% if request.user.channel %}
          <li><a class="dropdown-item" href="{% url 'channel:channelDetail' request.user.channel.id %}"><i class="fa-solid fa-table-columns"></i> Your Channel</a></li>
          {% else %}
          <li><a class="dropdown-item" href="{% url 'channel:createChannel' %}"><i class="fa-solid fa-square-plus"></i> Create Channel</a></li>
          {% endif %}
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="{% url 'account:logout' %}"><i class="fa-solid fa-right-from-bracket"></i> Sign out</a></li>
        </ul>
      </div>
      {% else %}
      <div class="text-end">
        <a href="{% url 'account:login' %}" class="btn btn-outline-light me-2"><i class="fa-solid fa-arrow-right-to-bracket"></i> Login</a>
        <a href="{% url 'account:signUp' %}" class="btn btn-outline-warning"><i class="fa-solid fa-up-right-from-square"></i> Sign Up</a>
      </div>
      {% endif %}
    </div>
  </div>
</header>