account/urls.py
from django.urls import path
from .views import *

app_name = "account"
urlpatterns = [
    path("login/", loginView, name="login"),
    path("sign_up/", signUp, name="signUp"),
    path("logout/", logoutView, name="logout"),

    # user
    path("profile/", userProfile, name="userProfile"),
    path("update/profile/", updateUserProfile, name="updateUserProfile"),
    path("change/password/", changeUserPassword, name="changeUserPassword"),
]

channel/urls.py
from django.urls import path
from .views import *


app_name = "channel"
urlpatterns = [
    path('channels/', channelList, name="channelList"),
    path('detail/<int:id>/', channelDetail, name="channelDetail"),
    path("create_channel/", createChannel, name="createChannel"),
    path("update_channel/<int:id>/", updateChannel, name="updateChannel"),
    path("delete_channel/<int:id>/", deleteChannel, name="deleteChannel"),

    # subscriptions
    path('subscriptons/', subscriptionsList, name="subscriptonsList"),

    path('channel/subscribe/<int:id>/', subscribeView, name="subscribeChannel"),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("video.urls")),
    path('channel/', include("channel.urls")),
    path('account/', include("account.urls")),
]

handler404 = "main.views.page_not_found_view"


static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from .views import *


app_name = "video"
urlpatterns = [
    path('', index, name="index"),
    path('watch/<slug:slug>/', videoDetail, name="detail"),
    path('create/video/', createVideo, name="createVideo"),
    path('delete/video/<int:id>/<slug:slug>/', deleteVideo, name="deleteVideo"),
    path('update/video/<int:id>/<slug:slug>/', updateVideo, name="updateVideo"),

    # sub and like
    path('watch/like/<int:id>/', likeView, name="likeVideo"),

    # library
    path('library/', userLibrary, name="userLibrary"),
    path('library/<int:id>/', userLibraryVideos, name="userLibraryVideos"),
    path('create/library/', userLibraryCreate, name="userLibraryCreate"),
    path('update/library/<int:id>/', userLibraryUpdate, name="userLibraryUpdate"),
    path('delete/library/<int:id>/', userLibraryDelete, name="userLibraryDelete"),

    path('add/library/video/<int:id>/<int:video_id>/', addLibraryVideo, name="addLibraryVideo"),
    path('remove/library/video/<int:id>/<int:video_id>/', removeLibraryVideo, name="removeLibraryVideo"),


    # like videos authorVideos
    path('like/videos', likeVideos, name="likeVideoList"),

    # author
    path('author/videos/', authorVideos, name="authorVideos"),

]

channel/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse
from django.utils.safestring import mark_safe


class Channel(models.Model):
    channel_name = models.CharField(
        max_length=120, verbose_name="Channel Name")
    slogan = models.CharField(max_length=100, verbose_name="Channel Slogan")
    subscribers = models.ManyToManyField(
        User, related_name="video_subscribers", blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = RichTextField(verbose_name="Description", blank=True)
    avatar = models.ImageField(upload_to='channel/avatar/', default="images/channel/avatar/avatar.png")
    banner_image = models.ImageField(upload_to='channel/banner_image/', default="images/channel/avatar/avatar.png")
    join_date = models.DateTimeField(
        verbose_name="Join Date", auto_now_add=True)
    
    def image_tag(self):
        if self.avatar:
            return mark_safe(f'<img src="{self.avatar.url}" height="100">')

    image_tag.short_description = "Image"
    image_tag.allow_tags = True

    def __str__(self):
        return self.channel_name

    def get_absolute_url(self):
        return reverse("channel:channelDetail", kwargs={'id': self.id})

    def get_update_url(self):
        return reverse('channel:updateChannel', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('channel:deleteChannel', kwargs={'id': self.id})

    def total_subscribers(self):
        return self.subscribers.count()

channel/forms.py
from django import forms
from .models import Channel
from ckeditor.fields import RichTextField


class ChannelForm(forms.ModelForm):
    class Meta:
        model = Channel
        fields = [
            'channel_name',
            'slogan',
            'description',
            'avatar',
            'banner_image'
        ]
        widgets = {
           'channel_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Channel Name'}),
           'slogan': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Channel Slogan'}),
           'description': RichTextField()
        }


channel/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from .models import Channel
from .forms import ChannelForm
from video.models import Video
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required
def subscribeView(request, id):
    if Channel.objects.filter(user_id=request.user.id).exists():
        channel = get_object_or_404(
            Channel, id=request.POST.get('video_subscribe_id'))
        
        if channel.user == request.user:
            messages.warning(request, 'You cannot subscribe to your own channel!')
            return redirect('channel:channelDetail', id=id)
        
        subscribe = False
        if channel.subscribers.filter(id=request.user.id).exists():
            channel.subscribers.remove(request.user)
            subscribe = False
        else:
            channel.subscribers.add(request.user)
            subscribe = True

        url = request.META.get('HTTP_REFERER')
    else:
        messages.warning(
            request, 'You must create a channel to subscribe channels!')
        return redirect('channel:createChannel')

    return HttpResponseRedirect(url)


def channelList(request):
    channels = Channel.objects.all()[:10]
    context = {
        'channels': channels,
    }
    return render(request, 'channel/channel_list.html', context)


def channelDetail(request, id):
    channel = Channel.objects.get(id=id)
    videos = Video.objects.filter(status="True", channel_id=id)

    subscribe = False
    if channel.subscribers.filter(id=request.user.id).exists():
        subscribe = True

    context = {
        'channel': channel,
        'videos': videos,
        'last_video': videos.last(),
        'subscribe': subscribe,
        'subscribe_total': channel.total_subscribers(),
    }


    return render(request, 'channel/channel_detail.html', context)


@login_required
def createChannel(request):
    if not Channel.objects.filter(user_id=request.user.id).exists():
        channelForm = ChannelForm(request.POST or None, request.FILES or None)
        if request.method == "POST":
            if channelForm.is_valid():
                channelForm.instance.user_id = request.user.id
                channel = channelForm.save()
                messages.success(
                    request, 'Your channel has been successfully created.')
                return HttpResponseRedirect(channel.get_absolute_url())
    else:
        userChannel = Channel.objects.get(user_id=request.user.id)
        messages.warning(request, 'You already own a channel!')
        return HttpResponseRedirect(userChannel.get_absolute_url())

    return render(request, 'channel/post/create_channel.html', {'channelForm': channelForm})


@login_required
def updateChannel(request, id):
    if Channel.objects.filter(user_id=request.user.id).exists():
        channel = Channel.objects.get(id=id, user_id=request.user.id)
        channelForm = ChannelForm(
            request.POST or None, request.FILES or None, instance=channel)
        if request.method == "POST":
            if channelForm.is_valid():
                channelForm.instance.user_id = request.user.id
                channelForm.save()
                messages.success(
                    request, 'Your channel has been successfully created.')
                return HttpResponseRedirect(channel.get_absolute_url())
    else:
        messages.warning(request, 'Please create your channel!')
        return redirect('video:createChannel')

    return render(request, 'channel/post/update_channel.html', {'channelForm': channelForm})


@login_required
def deleteChannel(request, id):
    if Channel.objects.filter(user_id=request.user.id).exists():
        channel = Channel.objects.get(id=id, user_id=request.user.id)
        try:
            channel.delete()
            messages.success(
                request, "Your channel has been successfully deleted.")
        except:
            messages.error(request, "Your channel could not be deleted!")
    else:
        messages.warning(request, 'Please create your channel!')
        return redirect('video:createChannel')

    return redirect('video:index')

@login_required
def subscriptionsList(request):
    channels = Channel.objects.filter(subscribers=request.user)
    videos = Video.objects.filter(channel__in=channels)
    context = {
        'channels': channels,
        'videos': videos
    }
    return render(request, 'channel/subscriptions_list.html', context)

templates/channel/channel_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block description %}{{channel.description|truncatechars:150}} · {% endblock description %}
{% block keywords %}{{channel.description|truncatechars:150}} · {% endblock keywords %}
{% block title %}{{channel.channel_name}} · {% endblock title %}
{% block content %}
<div class="container mt-3">
  {% include 'base/message.html' %}
    <div class="p-4 p-md-5 mb-4 text-white rounded" style="background-image: url('{% if channel.banner_image %}{{channel.banner_image.url}}{% else %} {% static '/images/channel/banner/sage.png' %} {% endif %}'); background-size: contain;">
      <div class="d-flex justify-content-center">
        {% if channel.avatar %}
          <img src="{{channel.avatar.url}}" alt="{{channel.channel_name}}" width="150" height="150" class="rounded-circle shadow-sm p-1 mb-1 bg-dark">
        {% else %}
          <img src="{% static 'images/channel/avatar/avatar.jpg' %}" alt="{{channel.channel_name}}" width="150" height="150" class="rounded-circle shadow-sm p-1 mb-1 bg-dark">
        {% endif %}
      </div>  
      <div class="col-md-6 px-0 h-100 text-white text-shadow-1" style="text-shadow: 0 0.25rem 0.5rem rgb(0 0 0 / 25%);">
          <h1 class="display-4 fst-italic rounded" style="text-shadow: 1px 1px #000000;">{{channel.channel_name}}</h1>
          <p class="lead my-3" style="text-shadow: 1px 1px #000000;">{{channel.slogan}}</p>
          <p class="lead my-3" style="text-shadow: 1px 1px #000000;">{{subscribe_total}} Subscribe</p>
        </div>
      </div>
      {% if user.is_authenticated %}
        {% if channel.user_id == request.user.id %}
        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Delete
        </button>
        <a href="{{channel.get_update_url}}" role="buton" class="btn btn-block btn-info btn-sm">Update</a>
        <a href="{% url 'video:createVideo' %}" role="buton" class="btn btn-block btn-warning btn-sm">New Video</a>
        {% endif %} 
      {% endif %}
      <div class="row g-3 align-items-center">
        {% if user.is_authenticated %}
            {% if not channel.user_id == request.user.id %}
              <form action="{% url 'channel:subscribeChannel' channel.pk %}" method="post">
                  {% csrf_token %}
                  {% if subscribe %}
                      <button type="submit" name="video_subscribe_id" value="{{channel.id}}" class="btn btn-secondary">Unsubscribe</button>
                  {% else %}
                      <button type="submit" name="video_subscribe_id" value="{{channel.id}}" class="btn btn-danger">Subscribe</button>
                  {% endif %} 
              </form>
            {% endif %}
        {% else %}
        <a href="{% url 'account:login' %}" class="btn btn-danger btn-sm" style="width:150px">Login to Subscribe</a>
        {% endif %}  
        <h4 class="text-start">Share</h4>
        <!-- AddToAny BEGIN -->
        <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
          <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
          <a class="a2a_button_facebook"></a>
          <a class="a2a_button_twitter"></a>
          <a class="a2a_button_email"></a>
          <a class="a2a_button_whatsapp"></a>
          <a class="a2a_button_telegram"></a>
          <a class="a2a_button_linkedin"></a>
        </div>
        <script async src="https://static.addtoany.com/menu/page.js"></script>
        <!-- AddToAny END -->
      </div>
      
      <div class="row mb-5">
        <div class="col-4">
          <div class="list-group" id="list-tab" role="tablist">
            <a class="list-group-item list-group-item-action" id="list-home-list" data-bs-toggle="list" href="#list-home" role="tab" aria-controls="list-home">Home</a>
            <a class="list-group-item list-group-item-action" id="list-videos-list" data-bs-toggle="list" href="#list-videos" role="tab" aria-controls="list-videos">Videos</a>
            <a class="list-group-item list-group-item-action" id="list-about-list" data-bs-toggle="list" href="#list-about" role="tab" aria-controls="list-about">About</a>
          </div>
        </div>
        <div class="col-8">
          <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
                <div class="ratio ratio-16x9">
                  {% if last_video %}
                    <div class="card mb-3">
                        <video  width="100%" height="100%" controls autoplay>
                            <source src="{{last_video.video.url}}" type="video/mp4" />
                        </video>
                        <div class="card-body">
                          <h5 class="card-title">{{last_video.title}}</h5>
                          <p class="card-text">{{last_video.content|safe|linebreaks|truncatechars:100}}</p>
                          <p class="card-text"><small class="text-muted">{{last_video.publishing_date|date:"M d, Y"}}</small></p>
                          <a href="{{last_video.get_absolute_url}}" class="btn btn-block btn-info">See More</a>
                          {% if user.is_authenticated %}
                            {% if channel.user_id == request.user.id %}
                          <a href="{{last_video.get_update_url}}" role="buton" class="btn btn-block btn-primary">Update</a>
                            {% endif %}
                          {% endif %}
                        </div>
                    </div>
                  {% else %}
                  <div class="text-center">
                    <div class="alert alert-success text-center" role="alert">
                      Video will be added soon...
                    </div>
                  </div>
                  {% endif %}
                </div>
            </div>
            <div class="tab-pane fade" id="list-videos" role="tabpanel" aria-labelledby="list-videos-list">
                <div class="row row-cols-1 row-cols-sm-2 ">
                  {% if videos %}
                    {% for video in videos %}
                    <a href="{{video.get_absolute_url}}"  class="m-1 h-25" style="text-decoration: none; width: 25rem;">
                        <div class="col">
                          <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('{{video.cover_image.url}}');">
                            <div class="d-flex flex-column h-50 p-5 pb-3 text-white text-shadow-1">
                              <h2 class="pt-5 mt-5 mb-4 fs-5 lh-1 fw-bold">{{video.title}}</h2>
                              <ul class="d-flex list-unstyled mt-auto">
                                <li class="me-auto">
                                  {% if video.channel.avatar %}
                                    <img src="{{video.channel.avatar.url}}" alt="Bootstrap" width="40" height="40" class="rounded-circle border border-white">
                                  {% else %}
                                    <img src="https://github.com/twbs.png" alt="Bootstrap" width="40" height="40" class="rounded-circle border border-white">
                                  {% endif %}
                                </li>
                                <li class="d-flex align-items-center me-3">
                                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                                  <small>{{video.user.channel.channel_name|upper}}</small>
                                </li>
                                <li class="d-flex align-items-center">
                                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                                  <small>{{video.publishing_date|timesince}} ago</small>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                    </a>
                    {% endfor %}
                  {% else %}
                  <div class="text-center">
                    <div class="alert alert-success text-center" role="alert">
                      Videos will be added soon...
                    </div>
                  </div>
                  {% endif %}
                </div>
            </div>
            <div class="tab-pane fade" id="list-about" role="tabpanel" aria-labelledby="list-about-list">
                <h1 class="display-4 fst-italic">{{channel.channel_name}} <span class="fs-5">Join Date ({{channel.join_date|date:"M d, Y"  }})</span></h1>
                <p class="lead mb-0">{{channel.description|safe|linebreaks}}</p>
                <p class="lead mb-0">Email: {{channel.user.email}}</p>
            </div>
          </div>
        </div>
      </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Channel</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p class="fw-bolder" >Are you sure you want to delete {{channel.channel_name|upper}} channel?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a href="{{channel.get_delete_url}}" role="buton" class="btn btn-block btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}


templates/channel/channel_list.html
{% extends 'base/base.html' %}
{% load static %}
{% block description %}All Channel List · {% endblock description %}
{% block keywords %}All Channel List · {% endblock keywords %}
{% block title %}All Channel List · {% endblock title %}
{% block content %}
<div class="container mt-3">
  {% if channels %}
  <div class="row row-cols-1 row-cols-md-3 g-4">
  {% include 'base/message.html' %}
    {% for channel in channels %}
    <div class="col">
      <div class="card">
        <img src="{{channel.avatar.url}}" class="card-img-top img-responsive" alt="{{channel.channel_name}}">
        <div class="card-body text-center">
          <h5 class="card-title">{{channel.channel_name}} ({{channel.total_subscribers}} subscribers)</h5>
          <p class="card-text">{{channel.description|safe}}</p>
          <a href="{{channel.get_absolute_url}}" class="btn btn-sm stretched-link text-light" style="background-color:#6610f2">Go Channel</a>
        </div>
        <div class="card-footer">
          <small class="text-muted">{{channel.slogan}}</small>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
    {% else %}
      <div class="text-center mt-5">
        <div class="alert alert-success text-center" role="alert">
          Channels will be added soon...
        </div>
      </div>
    {% endif %}
</div>


{% endblock content %}

templates/channel/library.html
{% extends 'base/base.html' %}
{% load static %}
{% block description %}({{request.user.username|upper}}) Library · {% endblock description %}
{% block keywords %}({{request.user.username|upper}}) Library · {% endblock keywords %}
{% block title %}({{request.user.username|upper}}) Library · {% endblock title %}
{% block content %}
<div class="container mt-3">
{% include 'base/message.html' %}
<div class="row g-5">
    <div class="col-lg-12">
      <h3 class="pb-4 mb-2 fst-italic border-bottom">
        Enjoy your favorite videos 
        {% if request.user.is_authenticated %}
          <a href="{% url 'video:userLibraryCreate' %}" class="btn btn-sm btn-warning">Create List</a>
        {% endif %}
      </h3>
      
      <article class="blog-post">
        {% if request.user.is_authenticated %}
            {% if watchLaterVideos %}
            <div class="row">
              {% for item in watchLaterVideos %}
                <div class="col-sm-6">
                    <div class="card border-danger">
                        <div class="card-header">{{item.channel.channel_name}} <i class="fa-solid fa-lock{% if item.private == "True" %}-open{% endif %}"></i></div>
                        <div class="card-body">
                          <h5 class="card-title">{{item.title}}</h5>
                          <p class="card-text">{{item.totalVideos}} Videos · {{item.date|date:"M d, Y"}}</p>
                        </div>
                        <a href="{{item.get_absolute_url}}" class="btn  btn-sm btn-dark">Watch Videos</a>
                        <a href="{{item.get_update_url}}" class="btn btn-sm btn-primary">Update List</a>
                      </div>
                </div>
              {% endfor %}
            </div>
            {% else %}
            <div class="text-center mt-5">
              <div class="alert alert-success text-center" role="alert">
                
                Create a list to access the videos you like or save. <a href="{% url 'video:userLibraryCreate' %}" class="btn btn-sm btn-warning">Create New List</a>
              </div>
          </div>
            {% endif %}
        {% else %}
            <div class="text-center mt-5">
                <div class="alert alert-success text-center" role="alert">
                    Sign in to access the videos you like or save. <a href="{% url 'account:login' %}" class="alert-link">Log in <i class="fa-solid fa-right-to-bracket"></i></a>
                </div>
            </div>
        {% endif %}
      </article>
    </div>
  </div>
</div>
{% endblock content %}

templates/channel/libraryVideos.html
{% extends 'base/base.html' %}
{% load static %}
{% block description %}All Channel List · {% endblock description %}
{% block keywords %}All Channel List · {% endblock keywords %}
{% block title %}All Channel List · {% endblock title %}
{% block content %}
<div class="container mt-3">
{% include 'base/message.html' %}
<div class="row g-5">
    <div class="col-lg-12">
      <h3 class="pb-4 mb-2 fst-italic border-bottom">
        {{library.title}} <small>({{library.date|date:"M d, Y"}})</small>
        {% if request.user.is_authenticated %}
          <a href="{{library.userLibraryDelete}}" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete List</a>
          <a href="{{library.get_update_url}}" class="btn btn-sm btn-warning">Update List</a>
          <a href="{% url 'video:userLibraryCreate' %}" class="btn btn-sm btn-warning">Create New List</a>
        {% endif %}
      </h3>
      
      <article class="blog-post">
        {% if request.user.is_authenticated %}
          <div class="row row-cols-1 row-cols-md-2 g-4">
          {% for video in videos %}
            <div class="card" style="width: 18rem;">
              <img class="card-img-top" src="{{video.cover_image.url}}" alt="{{video.title}}">
              <div class="card-body">
                <h5 class="card-title">{{video.title}}</h5>
                <p class="card-text">{{video.channel.channel_name}} · {{video.publishing_date|date:"M d, Y"}}</p>
                <a href="{{video.get_absolute_url}}" class="btn btn-primary">Watch Video</a>
                <form action="{% url 'video:removeLibraryVideo' library.id video.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger">Remove</button>
                </form>
              </div>
            </div>
          {% endfor %}
        </div>
        {% else %}
            <div class="text-center mt-5">
                <div class="alert alert-success text-center" role="alert">
                    Sign in to access the videos you like or save. <a href="{% url 'account:login' %}" class="alert-link">Log in <i class="fa-solid fa-right-to-bracket"></i></a>
                </div>
            </div>
        {% endif %}
      </article>
    </div>
  </div>
</div>

<!-- List -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete List</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p class="fw-bolder" >Are you sure you want to delete {{library.title|upper}} list?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a href="{{library.get_delete_url}}" role="buton" class="btn btn-block btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/channel/subscriptions_list.html
{% extends 'base/base.html' %}
{% block description %}Subscribtions List · {% endblock description %}
{% block keywords %}Subscribtions List · {% endblock keywords %}
{% block title %}Channels subscribed to {{channel.channel_name}} · {% endblock title %}
{% load static %}
{% block content %}
<div class="container mt-3">
  <div class="row">
    {% if request.user.is_authenticated %}
      <div class="col-lg-3">
        <h3 class="pb-4 mb-2 fst-italic border-bottom">
          Subscribtions Channels
        </h3>

        <div class="list-group">
            {% if channels %}
              {% for channel in channels %}
                <a href="{% url 'channel:channelDetail' channel.pk %}" class="list-group-item d-flex justify-content-between align-items-center">{{channel.channel_name}}<span class="badge bg-primary rounded-pill">{{channel.total_subscribers}} subscribes</span></a>
              {% endfor %}
            {% endif %}
        </div>
      </div>

      <div class="col-lg-9 mt-3">
        <div class="row row-cols- row-cols-lg-3 align-items-stretch">
          {% if videos %}
            {% for video in videos %}
              <a href="{{video.get_absolute_url}}" class="h-25 p-1" style="text-decoration: none;">
                <div class="col">
                  <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('{{video.cover_image.url}}');">
                    <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-2">
                      <h5 class="pt-5 mt-5 mb-4 lh-1 fw-bold" style="text-shadow: 1px 1px #000000;">{{video.title}}</h5>
                      <ul class="d-flex list-unstyled mt-auto">
                        <li class="me-auto">
                          {% if video.channel.avatar %}
                            <img src="{{video.channel.avatar.url}}" alt="Bootstrap" width="40" height="40" class="rounded-circle border border-white">
                          {% else %}
                          <img src="https://github.com/twbs.png" alt="Bootstrap" width="40" height="40" class="rounded-circle border border-white">
                          {% endif %}
                        </li>
                        <li class="d-flex align-items-center me-3">
                          <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                          <small style="text-shadow: 1px 1px #000000;">{{video.user.channel.channel_name}}</small>
                        </li>
                        <li class="d-flex align-items-center">
                          <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                          <small style="text-shadow: 1px 1px #000000;">{{video.publishing_date|date:"M d, Y"}} ago</small>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </a>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      {% else %}
        <div class="text-center mt-5">
          <div class="alert alert-success text-center" role="alert">
            You are not subscribed to any channel. <a href="{% url 'channel:channelList' %}" class="alert-link">Explorer Channels <i class="fa-solid fa-compass"></i></a>
          </div>
        </div>
      {% endif %}
  </div>
</div>
{% endblock content %}